# Generated by Django 3.2.24 on 2024-02-25 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_playervehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(max_length=150)),
                ('achievement_description', models.TextField(max_length=250)),
                ('date_achieved', models.DateTimeField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
        ),
    ]
